Repository S2GBird/.github, pull requests merged in 2023-12, with the labels that each got.

#38 Add Google authentication
  backend/app.js
  backend/config/googleAuthConfig.js
  backend/controllers/authController.js
  backend/package-lock.json
  backend/package.json
  backend/routes/auth/authIndex.js
Labels: changes requested

#45 adding jest to backend
  backend/package-lock.json
  backend/package.json
  backend/routes/__test__/back.test.js
  backend/sum.js
  frontend/__mocks__/filemocks.js
  frontend/__mocks__/stylemocks.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Pages/Login Page/LoginPage.jsx
  frontend/src/__test__/Login.test.js
Labels: unit testing

#47 Hotfix/user id authlogin
  backend/controllers/authController.js
Labels: HotFix

#48 Login functionality
  backend/config/googleAuthConfig.js
  backend/controllers/authController.js
  frontend/src/Pages/App/App.jsx
  frontend/src/Pages/Dashboard/Dashboard.jsx
  frontend/src/Pages/Dashboard/Dashboard.module.css
  frontend/src/Pages/Login Page/Login.module.css
  frontend/src/Pages/Login Page/LoginPage.jsx
  frontend/src/Services/apiClient.js
Labels: enhancement
